ALTER TABLE "Drawing" ADD COLUMN IF NOT EXISTS "approvalStatus" TEXT;
ALTER TABLE "Drawing" ADD COLUMN IF NOT EXISTS "approvalComment" TEXT;
ALTER TABLE "Drawing" ADD COLUMN IF NOT EXISTS "approvalDate" TIMESTAMP(3);
ALTER TABLE "Drawing" ADD COLUMN IF NOT EXISTS "approvedById" TEXT;
